name: CI
on:
  push:
    branches:
      - release # Default release branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'
      - name: Setup Mono 
        run: sudo apt install mono-devel
      - name: NuGet login (Trusted Publisher)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v2.0.1
        with:
         nuget-api-key: ${{steps.login.outputs.NUGET_API_KEY}}
          
      # TEMP: nuget push SPCCSHelpers.*.nupkg -Source https://api.nuget.org/v3/index.json
      - name: Publish to Nuget API and GitHub Packages
        run: |
          dotnet pack -c Release -o out
          cd out
          dotnet nuget push SPCCSHelpers.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{steps.login.outputs.NUGET_API_KEY}}
          dotnet nuget add source --username itachi1706 --password $GITHUB_TOKEN --store-password-in-clear-text --name github "https://nuget.pkg.github.com/itachi1706/index.json"
          dotnet nuget push SPCCSHelpers.*.nupkg  --api-key $GITHUB_TOKEN --source "github"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
